"""add fatura_periodo to transacao

Revision ID: 1fccebb1a224
Revises: c9242f722dab
Create Date: 2026-04-18 17:48:48.235348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fccebb1a224'
down_revision = 'c9242f722dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fatura_periodo', sa.String(length=7), nullable=True))
        batch_op.alter_column('anexo',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.alter_column('anexo',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.drop_column('fatura_periodo')

    # ### end Alembic commands ###
