"""add cor and icone

Revision ID: 233e9b63e349
Revises: 1fccebb1a224
Create Date: 2026-04-18 17:55:21.937682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '233e9b63e349'
down_revision = '1fccebb1a224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('icone', sa.String(length=50), nullable=True))

    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.alter_column('anexo',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.alter_column('anexo',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('icone')
        batch_op.drop_column('cor')

    # ### end Alembic commands ###
