"""add anexo to transacao

Revision ID: c9242f722dab
Revises: cc5dc77541d1
Create Date: 2026-04-18 15:21:41.997597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9242f722dab'
down_revision = 'cc5dc77541d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anexo', sa.LargeBinary(length=4294967295), nullable=True))
        batch_op.add_column(sa.Column('anexo_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.drop_column('anexo_filename')
        batch_op.drop_column('anexo')

    # ### end Alembic commands ###
